# Build project and storybook
# Deploy Storybook to dev-int.teams.microsoft.com
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - docs
      - README.md
      - SECURITY.md
      - CODE_OF_CONDUCT.md

pool:
  name: Hosted
  demands: azureps

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: "yarn"
    displayName: "Install Dependencies"

  - script: "yarn build"
    displayName: "Build Project"

  - script: "yarn test"
    displayName: "Validate Tests"
    enabled: false

  - script: "yarn build:storybook"
    displayName: "Build Storybook"

  - task: AzureFileCopy@2
    displayName: "Deploy Storybook to AzureBlob"
    inputs:
      SourcePath: "$(StorybookDist)"
      azureSubscription: "1841dd85-773f-40aa-81e7-9e926c104571"
      Destination: AzureBlob
      storage: "teamsuitemplate"
      ContainerName: "teamsuitemplate"
      BlobPrefix: "$(DirectoryName)"

  - task: AzurePowerShell@3
    displayName: "Update Blob Cache Control and Content Type"
    inputs:
      azureSubscription: "1841dd85-773f-40aa-81e7-9e926c104571"
      ScriptPath: scripts/UpdateBlobProperties.ps1
      ScriptArguments: "-StorageAccountName 'teamsuitemplate' -ContainerName 'teamsuitemplate' -ResourceGroupName 'TeamsApps'"
      azurePowerShellVersion: LatestVersion
